### ISSUE TITLE
Research and plan networking setup

### ISSUE THREAD

**Issue by tommeredith14** [uwrobotics/MarsRover2019#13]
Leave any non code instructions in a readme file

**Comment by wmmc88** [comment]
depends on outcome of #20

Tentatively:
Asus 2.4 ghz basestation
Ubiquity 900mhz rover + basestation
jetson 2.4ghz access point w/ enhanced antennas
?do we need bluebeam antenna? --> weight conservation

**Comment by wmmc88** [comment]
will need multimaster if double network
